Update RIO profile
SURFnet/eduhub-validator pull request #8
Opened 2023-12-05 13:56 UTC by jelmerderonde

This PR updates the RIO profile and adds `/.clj-kondo` to `.gitignore`.

2024-01-08 11:05 UTC, jelmerderonde commented
@joodie heb jij een kans om dit (kort) te reviewen? Of zal ik het zelf even mergen?

2024-01-09 08:13 UTC, joodie requested changes

2024-01-09 08:13 UTC, joodie commented
@jelmerderonde sorry ik had mijn review al wel gedaan maar niet opgeslagen. bij deze

2024-01-10 07:50 UTC, jelmerderonde commented on profiles/rio
> +                               "consumer" "rio"}}]}]}
I've fixed it!

2024-01-10 08:32 UTC, joodie approved these changes

2024-01-10 09:53 UTC, merged